### ISSUE TITLE
Infinite Error Loop?

### ISSUE THREAD

**Issue by kendallvision** [Jon-Peppinck/linkedin-clone#3]
Learned a lot from this.  Thank you!

https://github.com/Jon-Peppinck/linkedin-clone/blob/1985bfab5e50d34597979cd667ceaf77cf808075/api/src/core/all-exceptions.filter.ts#L69

Wouldn't the exceptions keep looping infinitely if an error occurs while writing to the error file?

**Comment by Jon-Peppinck** [comment]
Good call. It is most likely this would fail if the server is out of memory. In the unlikely case that there is a problem writing to the file and the error logging function errors, perhaps instead of throwing an error we could use some monitoring and or analytical tool, such as Sentry or Google analytics event. Otherwise, we could retry writing to the file once in a try catch and otherwise ignore it. But it probably is something we would want to be aware of in a production app.
